export const users = [
  {
    name: "Aarav Sharma",
    email: "aarav@example.com",
    age: 25,
    role: "Developer",
    city: "Ahmedabad",
  },
  {
    name: "Diya Patel",
    email: "diya@example.com",
    age: 23,
    role: "Designer",
    city: "Surat",
  },
  {
    name: "Rohan Mehta",
    email: "rohan@example.com",
    age: 28,
    role: "Backend Engineer",
    city: "Mumbai",
  },
  {
    name: "Isha Shah",
    email: "isha@example.com",
    age: 24,
    role: "Frontend Developer",
    city: "Pune",
  },
  {
    name: "Kunal Verma",
    email: "kunal@example.com",
    age: 30,
    role: "Project Manager",
    city: "Delhi",
  },
  {
    name: "Neha Joshi",
    email: "neha@example.com",
    age: 27,
    role: "QA Engineer",
    city: "Bangalore",
  },
  {
    name: "Raj Malhotra",
    email: "raj@example.com",
    age: 29,
    role: "DevOps Engineer",
    city: "Hyderabad",
  },
  {
    name: "Sneha Iyer",
    email: "sneha@example.com",
    age: 26,
    role: "UI/UX Designer",
    city: "Chennai",
  },
  {
    name: "Vikram Singh",
    email: "vikram@example.com",
    age: 32,
    role: "Tech Lead",
    city: "Jaipur",
  },
  {
    name: "Pooja Gupta",
    email: "pooja@example.com",
    age: 22,
    role: "Intern",
    city: "Kolkata",
  },
  {
    name: "Arjun Nair",
    email: "arjun@example.com",
    age: 31,
    role: "Full Stack Developer",
    city: "Kochi",
  },
  {
    name: "Meera Kapoor",
    email: "meera@example.com",
    age: 27,
    role: "Product Manager",
    city: "Delhi",
  },
  {
    name: "Siddharth Jain",
    email: "sid@example.com",
    age: 29,
    role: "Software Engineer",
    city: "Indore",
  },
  {
    name: "Ananya Das",
    email: "ananya@example.com",
    age: 24,
    role: "Data Analyst",
    city: "Bhubaneswar",
  },
  {
    name: "Yash Thakur",
    email: "yash@example.com",
    age: 28,
    role: "Security Engineer",
    city: "Nagpur",
  },
  {
    name: "Riya Sen",
    email: "riya@example.com",
    age: 26,
    role: "HR Manager",
    city: "Lucknow",
  },
  {
    name: "Aditya Rao",
    email: "aditya@example.com",
    age: 30,
    role: "Sales Manager",
    city: "Chandigarh",
  },
  {
    name: "Sanya Malhotra",
    email: "sanya@example.com",
    age: 25,
    role: "Marketing Specialist",
    city: "Gurgaon",
  },
  {
    name: "Karan Kapoor",
    email: "karan@example.com",
    age: 27,
    role: "Content Writer",
    city: "Noida",
  },
  {
    name: "Anjali Verma",
    email: "anjali@example.com",
    age: 26,
    role: "Content Strategist",
    city: "Noida",
  },
  {
    name: "Rahul Sinha",
    email: "rahul@example.com",
    age: 29,
    role: "Business Analyst",
    city: "Patna",
  },
  {
    name: "Priya Nair",
    email: "priya@example.com",
    age: 24,
    role: "Recruiter",
    city: "Kochi",
  },
  {
    name: "Dev Patel",
    email: "dev@example.com",
    age: 28,
    role: "Cloud Engineer",
    city: "Ahmedabad",
  },
  {
    name: "Nisha Gupta",
    email: "nisha@example.com",
    age: 25,
    role: "SEO Specialist",
    city: "Delhi",
  },
  {
    name: "Harsh Vyas",
    email: "harsh@example.com",
    age: 31,
    role: "Architect",
    city: "Ahmedabad",
  },
  {
    name: "Tanya Arora",
    email: "tanya@example.com",
    age: 23,
    role: "Graphic Designer",
    city: "Jaipur",
  },
  {
    name: "Mohit Bansal",
    email: "mohit@example.com",
    age: 30,
    role: "Operations Manager",
    city: "Delhi",
  },
  {
    name: "Simran Kaur",
    email: "simran@example.com",
    age: 26,
    role: "Social Media Manager",
    city: "Amritsar",
  },
  {
    name: "Nikhil Joshi",
    email: "nikhil@example.com",
    age: 27,
    role: "Machine Learning Engineer",
    city: "Pune",
  },
  {
    name: "Aisha Khan",
    email: "aisha@example.com",
    age: 24,
    role: "Support Engineer",
    city: "Bhopal",
  },
];
